amp: true
anomaly_clean: true
batch_size: 16
cuda: true
data_type: molecule
epochs: 40
freeze_layers: null
freeze_layers_reversed: false
kfold: 3
learning_rate: 0.0001
logger_level: 1
max_epochs: 100
max_norm: 5.0
metrics: mae
model_name: unimolv1
num_classes: 2
patience: 5
remove_hs: true
seed: 42
smi_strict: true
smiles_col: SMILES
split: random
split_group_col: scaffold
split_method: 3fold_random
split_seed: 42
target_col_prefix: TARGET
target_cols: TARGET0,TARGET1
target_normalize: auto
task: multilabel_regression
use_amp: true
use_cuda: true
warmup_ratio: 0.03
